config/routes.rb
Rails.application.routes.draw do
  get 'users/info'

  devise_for :users
  get 'info/infomovie'

  get 'info/infoimdb'

  get 'welcome/index'
  
  get '/users/info', to: 'users#info'
  post '/users/charge', to: 'users#charge'
  get '/users/cancel_subscription', to: 'users#cancel_subscription'

  resources :movies

  
   
  root 'movies#index'
   
   
   match 'searchmovie', to: 'info#infomovie', via: [:get, :post]
   
   
   get '/morefeature', :controller=>'morefeatures', :action=>'Input'
   post '/send' => 'morefeatures#Output'
   
   get  '/Latest' => 'morefeatures#Input'
   post '/Latest' => 'morefeatures#Latest'
   
   get  '/Person' => 'morefeatures#Input'
   post '/Person' => 'morefeatures#Person'
   
   
   
   
   
   
   

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
   before_filter :check_for_subscription, only: :show
  
  
 require 'info_controller'
  
  
  
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    
    
    if params[:search_movie].to_s.present?
       title = params[:search_movie]
      
    oMovie = InfoController.new
    @movie = oMovie.infomovie(title)
  #  debugger

    end
   # @movie = Movie.new(movie_params)


    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:Title, :Year      , :Released , :Genre ,  :Director , :Actors ,
                                    :Plot , :Language  , :Country  , :Poster , :imdb_ID  ,  :Production  )
    end
    
    def check_for_subscription
        unless current_user.subscription.active
        flash[:alert] = "You must be subscribed to access this content"
        redirect_to movies_path
        end
    end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_form.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
body {
    background-image: url("http://www.totalshortfilms.com/imagenes/principal.jpg");
    background-repeat: no-repeat;
    background-position: center;
    background-attachment: fixed;
}
</style>
</head>
<body>
  
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <%= form_tag("searchmovie", method: "post") do %>
	<%= label_tag(:search_movie, "Search for movie:") %>
	<%= text_field_tag(:search_movie) %>
	<%= submit_tag("Search Movie") %>
  <% end %>	
  
<% end %>


<%= link_to 'More||'  ,   morefeature_path %> 

</body>
</html>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Movies</h1>

<head>
<style>

body {
    background-image: url("https://0.s3.envato.com/files/94164686/Cinematic%20Bgs%20Pack.jpg");
    background-repeat: no-repeat;
    background-position: center;
    background-attachment: fixed;
}


div.films {
    background-color: black;
    color: white;
    margin: 20px 0 20px 0;
    padding: 20px;
}
</style>
</head>

<table>
  
<tbody>
  
     <% @movies.each do |movie| %>
      
     <div class="films">
       
          <p> Title:- <%= movie.Title %></p>
          <p> Plot:-  <%= movie.Plot %></p>
          <p> Director:- <%= movie.Director %></p>
          <p> Actors:- <%= movie.Actors %></p>
          <p> Genre:- <%= movie.Genre %></p>
          <p> Language:- <%= movie.Language %></p>
          <p> Country:- <%= movie.Country %></p>
          <p> Year:- <%= movie.Year %></p>
          <p> Production:- <%= movie.Production %></p>
          <p> Released:- <%= movie.Released %></p>
          <p><img src = <%= movie.Poster %> width="400" height="300"></p>
      
         <%= link_to 'Show', movie %></td>
         <%= link_to 'Edit', edit_movie_path(movie) %></td>
         <%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %>
         
   
      
     </div> 
      
    
    
    <% end %>
</tbody>

<%= link_to 'New Movie', new_movie_path %> || <%= link_to 'Subscribe', users_info_path %> || <%= link_to 'More', morefeature_path %>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<html>
<head>
<style>

body {
    
    background-image: url("http://blogv1.interaktifhizmetler.com/admin/resimler/tyfgfg5336.png");
    background-repeat: no-repeat;
    background-position: right top;
    margin-right: 200px;
    background-attachment: fixed;
}

img {
    
    background-image: url("https://cdn.vectorstock.com/i/composite/27,85/design-elements-of-movie-theme-design-vector-662785.jpg");
    border-radius: 8px;
}
</style>
</head>

<h1>Details of Movie</h1>

<body>
<p>
  <strong>Title:</strong>
  <%= @movie.Title %>
</p>

<p>
  <strong>Director:</strong>
  <%= @movie.Director %>
</p>

<p>
<p>
  <strong>Cast:</strong>
  <%= @movie.Actors %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @movie.Genre %>
</p>

<p>
  <strong>ImdbID:</strong>
  <%= @movie.imdb_ID %>
</p>

<p>
  <strong>Plot:</strong>
  <%= @movie.Plot %>
</p>

<p>
  <strong>Language:</strong>
  <%= @movie.Language %>
</p>

<p>
  <strong>Country:</strong>
  <%= @movie.Country %>
</p>

<p>
  <strong>Year:</strong>
  <%= @movie.Year %>
</p>

<p>
  <strong>Production:</strong>
  <%= @movie.Production %>
</p>

<p>
  <strong>Released:</strong>
  <%= @movie.Released %>
</p>

<p>
  <strong>Poster:</strong>
  <img src = <%= @movie.Poster %> width="400" height="300">
</p>


<%= link_to 'Edit', edit_movie_path(@movie) %> ||
<%= link_to 'Back', movies_path %>||

</body>
</html>