config/routes.rb
Rails.application.routes.draw do
  get 'users/info'

  devise_for :users
  get 'info/infomovie'

  get 'info/infoimdb'

  get 'welcome/index'
  
  get '/users/info', to: 'users#info'
  post '/users/charge', to: 'users#charge'
  get '/users/cancel_subscription', to: 'users#cancel_subscription'

  resources :movies

  
   
  root 'movies#index'
   
   
   match 'searchmovie', to: 'info#infomovie', via: [:get, :post]
   
   
   get '/morefeature', :controller=>'morefeatures', :action=>'Input'
   post '/send' => 'morefeatures#Output'
   
   get  '/Latest' => 'morefeatures#Input'
   post '/Latest' => 'morefeatures#Latest'
   
   get  '/Person' => 'morefeatures#Input'
   post '/Person' => 'morefeatures#Person'
   
   
   
   
   
   
   

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :subscription
  
  after_create :create_subscription
  def create_subscription
    Subscription.create(user_id: id) if subscription.nil?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter  :verify_authenticity_token
  before_action :authenticate_user!
  
  def info
      @subscription = current_user.subscription
      if @subscription.active
        @stripe_customer = Stripe::Customer.retrieve(@subscription.stripe_user_id)
        @stripe_subscription = @stripe_customer.subscriptions.first
      end
  end
  
  def cancel_subscription
       @stripe_customer = Stripe::Customer.retrieve(current_user.subscription.stripe_user_id)
        @stripe_subscription = @stripe_customer.subscriptions.first
        
        @stripe_subscription.delete
        current_user.subscription.active = false
        current_user.subscription.save
        
        redirect_to users_info_path
  end
  
  def charge
      token = params["stripeToken"]
      customer = Stripe::Customer.create( source: token, plan: 'mysubscriptionlevel1', email: current_user.email)
        
        current_user.subscription.stripe_user_id = customer.id
        current_user.subscription.active = true
        current_user.subscription.save
        
        redirect_to users_info_path
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<h4>Begin your $5.00 a month subscription</h4>
<form action="/users/charge" method="POST" id="payment-form">
<span class="payment-errors"></span>

<div class="row">
    <div class="col-md-6">
        <label>Card Number</label>
        <input class="form-control" type="text" size="20" data-stripe="number" placeholder="4242424242424242"/>
    </div>
</div>
<br>

 
<div class="row">
    <div class="col-xs-2">
        <label>CVC</label>
        <input type="text" data-stripe="cvc" class="form-control" placeholder="123"/>
    </div>
</div>
<br>

 
<div class="row">
    <div class="col-xs-2">
        <label>Expiration</label>
    </div>
</div>
 <div class="row">
    <div class="col-xs-1">
        <label>MM</label>
        <input class="form-control" type="text"  data-stripe="exp-month" placeholder="01"/>
    </div>
    <div class="col-xs-1">
    <label>YYYY</label>
    <input class="form-control" type="text"  data-stripe="exp-year" placeholder="2020"/>
    </div>
</div>

<div class="row">
<br/><button class="btn btn-primary" type="submit">Create Subscription</button>
</div>
</form>

<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
<script type="text/javascript"> 
    Stripe.setPublishableKey('pk_test_ZEZJ7vO3LgaXha7h5aJOYmFp');
    
    function stripeResponseHandler(status, response) {

      // Grab the form:
      var $form = $('#payment-form');
    
      if (response.error) { // Problem!
    
        // Show the errors on the form
        $form.find('.payment-errors').text(response.error.message);
        $form.find('button').prop('disabled', false); // Re-enable submission
    
      } else { // Token was created!
    
        // Get the token ID:
        var token = response.id;
    
        // Insert the token into the form so it gets submitted to the server:
        $form.append($('<input type="hidden" name="stripeToken" />').val(token));
    
        // Submit the form:
        $form.get(0).submit();
    
      }
    }

    jQuery(function($) {
        $('#payment-form').submit(function(event) {
        var $form = $(this);
        
        $form.find('button').prop('disabled', true);
        
        Stripe.card.createToken($form, stripeResponseHandler);
        
        return false;
        });
    });

</script>

app/views/users/info.html.erb
<h3>Account for <%= current_user.email %></h3>
<% if @subscription.active %>
     <h3>Current plan renews at: <%= Time.at(@stripe_subscription["current_period_end"]).strftime("%D") %></h3>
     
     <%= link_to "Cancel Subscription", users_cancel_subscription_path %>
<% else %>
    <%= render 'form' %>
<% end %>